name = "cf_ai_travel_chat"
main = "src/index.js"
compatibility_date = "2026-03-07"

[ai]
binding = "AI"

[assets]
directory = "./public"

[durable_objects]
bindings = [
  { name = "CHATROOM", class_name = "ChatRoom" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["ChatRoom"]